import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import UserInfo from './UserInfo';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div style={{ background: 'red', padding: '10px' }}>
          <p>This is the layout</p>
          <UserInfo />
        </div>
        {children}
      </body>
    </html>
  );
}
